### PR TITLE
use _id field for the session key

### PR DESCRIPTION
**Pull request by messa**
Proposing implementation of #11.

There could be some conflicts with my other PRs :) If you merge any PR I could rebase the rest so there will be no conflicts.

### CODE REVIEW

**Comment by alexpantyukhin** [comment]
Yes, please. Rebase your PR and I will merge it. Nice catch! Also please refer this to your issue for auto closing it wen the current PR will be merged.

**Comment by messa** [comment]
Rebased :)

**Comment by messa** [comment]
BTW. our other website uses Node.js and MongoDB with [connect-mongo](https://www.npmjs.com/package/connect-mongo) and their approach is the same – [src/index.js](https://github.com/jdesboeufs/connect-mongo/blob/master/src/index.js#L189)

**Comment by alexpantyukhin** [comment]
Thanks a lot!

**Pull request merged**
